language: go

go:
    - "1.5.1"

env:
    global:
        - SSH_KEY="travis_key"
        - GIT_NAME="Mattias Pernhult"
        - GIT_EMAIL="pernhultmattias@gmail.com"
        - SOURCE_DIR="public"
        - DEPLOY_BRANCH="source"

before_install:
    - openssl aes-256-cbc -K $encrypted_5badef0aa7c9_key -iv $encrypted_5badef0aa7c9_iv -in travis_key.enc -out travis_key -d

before_script:
    - go get -u -v github.com/spf13/hugo

script:
    - hugo

after_success:
    - ./scripts/deploy.sh
